apiVersion: v1
kind: Service
metadata:
  name: bud-credit-form-service
  labels:
    app: bud-credit-form
spec:
  selector:
    app: bud-credit-form
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP